### ISSUE TITLE
RFC fancy: Report nr of models defined/built

### ISSUE THREAD

**Issue by epa095** [equinor/gordo-controller#48]
The controller could do two things, which would be kind of cool:

- [X] When the `gordo` is seen it counts the nr of machines (so it would have to parse the config, that is the only lame part), and writes that nr into the status field of the gordo. (#50)
- [x] It watches the `models`, and as a new one arrives it counts the models for that gordo and updates the field in the corresponding gordo (it can find it from e.g. the ownerreference).

Then we could add these two fields to the kubectl printing, and you could see that X out of Y models is built.

**Comment by milesgranger** [comment]
Closed by #50
