### ISSUE TITLE
RFC: Retry failed models

### ISSUE THREAD

**Issue by epa095** [equinor/gordo-controller#9]
Today gordo-controller works in a  "fire-and-forget" manner: It starts the required workflows, and then the rest is up to the workflows. So it is up to the workflows to ensure that stuff works, and retry things which does not work. This has a few problems:
- Sometimes argo does not work as desired(!), e.g. it does not today retry "resource" templates, (i.e. the application of the service/deployment etc), so if something fails there it is just failed. Argo 2.4 might fix this.
- The retry-strategy is quite simple, it only takes a number (we use 5). But for unreadable tags we would maybe want some kind of exponential backoff, since they sometimes becomes readable again. There is no way of supporting this.
- We don't write back a status to the gordo, which would maybe be nice?

In general we dont "design for failure", which is probably a good idea since everything is alpha? So should maybe gordo-controller take a more active role? It could be designed as a kind of "fallback" which would retry stuff which argo fails at for various reasons. It could work as this (but remember this is a RFC!):
Every n seconds (e.g. n=60) it gets all gordo with status.Submitted > 0 and status.Done != True/timestamp/whatever. For each it does as follows:
- Read project_name, project_version (maybe generation?), and all gordo-models. 
- Remove all gordo-models which are taken care of by a running workflow (the models are stored in the metadata.annotation of the workflow)
- Remove all gordo-models which have a deployment (or service?) with the same version.
- If there are no remaining models then write Status: Done to the gordo.
- If there are remaining models: for all remaining gordo-models (i.e. the failed ones), make gordo-deploy start a new workflow with them, with the same project_name and project_version (important, otherwise it will delete stuff). 

Maybe sprinkle on some metadata about how many times a model has been retried (stored in the gordo's status maybe?) so it will not retry infinitely many times.

**Comment by milesgranger** [comment]
I like. Would another alternative be something like:
1. List all workflows which are in a `Failed` state; and get the owning `Gordo` from its metadata. (additional filtering from step 3)
2. Resubmit the Gordo which spawned that workflow.
3. Update the Gordo metadata with `n_attempts`, etc. Where we can try up to some maximum, and a `next_attempt_time`; with exponential backoff as some function of `n_attempts`.
4. And of course, a slick Slack message. :stuck_out_tongue_winking_eye:

**Comment by epa095** [comment]
Tja, but I was kind of wanting to avoid resubmitting the whole gordo, since if e.g. 50 out of 2000 models fails, I just wanted to resubmit the failed 50 ones to gordo-deploy

**Comment by milesgranger** [comment]
I was considering the spiffy model caching, but maybe if a disparity such as only 50 out of 2000+ models fail, it might be worth the added complexity to only resubmit failed models rather than the extra load of scheduling all those pods.
